### ISSUE TITLE
Payment not completed

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#232]
I took two payments today (07-01-2020) One payment of $96.40 for Kimberly Everly, For her pets Balto  and Bug. And the other payment of $16 for Wanda Wall, For her pet Mama. Neither of these payments went through. I clicked Submit after they paid, But for some reason, it was taking longer to go through and I had Other clients to take care of, so I refreshed the page. I didn't want to add the payment twice, just in case it was a problem with the system. 
(Both transactions were completed with a credit card.)

**Comment by carl-hamlin** [comment]
Yep. Please don't do that. If something is taking a while to go through, open a new tab in your browser and log into BARKS. Nothing stops you from having two running instances, so please let stalled processes resolve themselves instead of refreshing the page. I'll take care of these payment records.

**Comment by carl-hamlin** [comment]
Neither payment actually went through, so I manually entered them into the database with the correct date. Thank you for reporting this issue. I'm closing it now.
