### ISSUE TITLE
Pets in wrong account

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#367]
Peggy Morley (CID 1142) came in today to pick up medication for her pet Kadee, while taking her payment I noted that she has an outstanding bill for her pet Molly (AID 3583). Peggy does not own a dog named Molly and would like her removed. She believes most the pets on her account belong to the humane society. The othe pets not belonging to Peggy are, Benji (3300), Boots (3541), Elvis(3301), Lola (3498), and Tex (3499). She says she has never owned any of those pets and would like them off the account. Thanks

**Comment by carl-hamlin** [comment]
This has been fixed. The problem here, apparently, was that she was bringing a shit ton of animals in for the Humane Society proper, and of course we were linking them to her as a caretaker and potential contact for lack of payment.

BUT THEN...

All that shit went down with the Humane Society last year, and Dr. Simko and I made the decision to internally disconnect the Humane Society from pets that had come in for FFP and sponsored services, so that when the Humane Society account pets all had gone three years without a visit, we could smoke the goddamned account and free up some space in the database for, y'know, real clientele.

However, Humane Society Couriers slipped through the cracks and once the Big Disconnect was enacted, they became the sole caretakers of animals for whom they had provided taxi service, instead of the Humane Society. I'll bet you this happens at least once more before we're done with it.

In Peggy's case, however, the issue is resolved.
