### ISSUE TITLE
Coat Patterns

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#614]
Well, I had this all written out yesterday and my computer crashed so it's all gone now. 
So, looking on google has not been very helpful, but the gist you already have in the system. All I can see is missing is the colorpoint for cats which are for the Siamese type breeds. I cannot find anything missing for dog's even though clients will tell me "the dog is such and such breed with such and such coat" So I will just update this when I find new or more coat patterns.
EDIT: Colorpoint includes but is not limited to; 
**Colors:**
Snoeshoe
Seal point
Cream point
Flame point (also called red point)
Cinnamon point
Fawn point
Chocolate point
Blue point
Lilac point
**Patterns:**
Solid point (in any of the colors)
Lynx (tabby) point (in any of the colors)
Tortie point (in any of the colors)
Torbie point (in any of the colors)

### **_TABBY_**
Tabby's have different types!!! including Mackerel, Blotched, Spotted, and Ticked. 

AND for dogs i believe you have them all except Bi-color and tri-color, But it looks like you can just say patched or flashy or tuxedo(which you have) for bi-color and for tri-color does not seem to have a word for it.
I don't know if we need dapple since we have merle 
And then you'll need saddle and sable for like german shepard breeds.
EDIT:

**Comment by carl-hamlin** [comment]
> Well, I had this all written out yesterday and my computer crashed so it's all gone now.

Technology is a bitch.

> So, looking on google has not been very helpful, but the gist you already have in the system.

Yes.

> All I can see is missing is the colorpoint for cats which are for the Siamese type breeds.

OK. I'll add those, although I'm not sure it's necessary to do so. Better to overprepare, I suppose.

> I cannot find anything missing for dog's even though clients will tell me "the dog
> is such and such breed with such and such coat" So I will just update this when
> I find new or more coat patterns.

Coat patterns tend to be more of a 'I need this right now' thing, so instead of updating this issue, please text me and say "I'm entering a new client and I need a new coat pattern called 'Burnished Lavender' or whatever the fuck pretentious bullshit the client is feeding you, and we can decide together whether we're catering to that crap or not in real time.

> EDIT: Colorpoint includes but is not limited to; <continues with point values>

I have added the points, but omitted patterns - they're superfluous. This went better than expected, I only had to put real effort into suppressing the gag reflex when I got to 'Lilac Point'. If you're the type of person who insists that your veterinarian correctly identify your Siamese as a 'lilac point' then for my money, you can go fuck yourself.

> Tabby's have different types!!! including Mackerel, Blotched, Spotted, and Ticked.

They do indeed! And in our system, they're all called 'Tabby'.

> AND for dogs i believe you have them all except Bi-color and tri-color, But it looks
> like you can just say patched or flashy or tuxedo(which you have) for bi-color and
> for tri-color does not seem to have a word for it.

I believe you've apprehended the situation admirably.

> I don't know if we need dapple since we have merle

We don't. Use merle.

> And then you'll need saddle and sable for like german shepard breeds.

Added, against my better judgement.

Allowed to roll unchecked, coat patterns could potentially become a wild, unruly mess of conflicting options, all of which will fall directly into my lap once it comes maintenance time, and enough of BARKS has already gone there that I'll be thrice damned before I allow one more goddamned table to traverse that well travelled path. Coats will remain simple. The line is drawn here, and the chaos shall advance NO FURTHER.

That having been said, I'm leaving this issue open until next week just in case you come up with a few more well-reasoned additions to the table, then I'm closing the issue, locking it up, and tasking a group of midgets and madmen to take the key to be thrown into a volcano somewhere, so work fast and above all... choose wisely.

**Comment by carl-hamlin** [comment]
No new coat patterns. I'm closing this issue. Contact me directly if you need something added to the table, and be prepared to hear the word 'no'.
