### ISSUE TITLE
Wrong date on vaccine

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#721]
Client Bobby Marques ID#2299, Pet Tuco ID#5710.   DHLPP Vaccine date and expired date same 03-03-2020.

**Comment by carl-hamlin** [comment]
Righto. The vaccine line item used on 3.3.2020 is the old style vaccine without the tracking interval. That line item is no longer able to be entered, because without a tracking interval we're not able to make a determination as to when it expires. When Tuco comes back in for another vaccine, that tracker will update with the new tracking interval.
