### ISSUE TITLE
Fix Phone Number

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#754]
I just tried to add a phone number to Mary Delgado's account CID 659.
I accidentally added a space in the number. Now the place disappeared where the phone numbers should be.
Phone number is 2093313864 
Could you fix this?

**Comment by carl-hamlin** [comment]
This issue is what is known as a 'regression'. Regression happens when something that was a problem gets fixed, then the angels sing for a bit, and then... the problem comes back.

Usually, this has to do with aggressive weave interpolation on my part during development - I misinterpret a notice from the repository control software indicating that a new commit is merging incorrectly, and inadvertently apply old code over new.

The headline here is that you didn't do anything wrong - we've come to the conclusion that it's futile to assume that the staff will not insert non-numeric characters into numeric fields, and as such have placed mechanisms into the software to sanitize those inputs prior to passing them on to the server, and in this instance, one of those mechanisms has been clobbered by a new commit somewhere, and now I have a little detective work to do, with myself as the prime suspect.

Work on this issue will be logged to Bug #667 but resolution will be logged here. Good catch, Loren.

**Comment by carl-hamlin** [comment]
Fixed via commit 072457c529a4d61ab68a0e2e06a1c311b26f5f69 (b.667)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Jul 13 13:11:30 2022 -0700

Closing issue.
