### ISSUE TITLE
Patient Name/Gender Change AID  10007

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#768]
Change Gabby to Gabe
F to NM

**Comment by carl-hamlin** [comment]
Fixed.

While we're here, I've noticed that you ask for 'NM' and 'SF' for gender changes. Internally, BARKS keeps track of gender and sterilization as two separate metrics - the animal is either intact or not, and the animal is either 'M' or 'F'.

I don't care if you continue to ask for 'NM' and 'SF' because I know what you mean, but I thought I should probably clear up how the insides of BARKS work with regard to gender and sterilization, just in case there was a misunderstanding.

**Comment by julsneves** [comment]
Alrighty…I will try to remember that.😌

**Comment by julsneves** [comment]
Got it.  Thank you sir!
