### ISSUE TITLE
Add Coat Pattern

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#772]
Add grizzle to coat pattern data base

**Comment by carl-hamlin** [comment]
Loren, et.al:

When we first introduced coat patterns to the BARKS database, I was very, very clear concerning the line in the sand that I was drawing here with regard to database hygiene and added maintenance costs.

Now, I understand that this issue is the result of a mucky-muck needing to invent some reason for you to be wrong, and not even a current client at that. This issue was largely created to get some ridiculous primate to stop shitting into her own hand and flinging it at the window, and that's fine as far as that goes; we do what we must to move the day along.

However, I'll re-iterate here for all in earshot - unless someone brings in a coat pattern that is utterly, uniquely unlike anything we already have in the database, I'm going to shoot new suggestions for coat (and, indeed most list-orientatae) down like a sleep addled quail. We're *NOT* polluting the database with redundancy. There's enough going on there already to give me headaches for the next several years, and I'm slowly but surely carving back the backlog of weeds.

So. No. If some grunting troglodyte approaches the window with a shrill whine concerning her dog's coat pattern 'technically' being 'grizzle' instead of 'sable', you can officially tell them that word from on high is that they can take their 'sable' marked invoice, fold it tightly until it's all sharp corners, and insert it as deeply into their diseased rectums as they can reach.

Please, by all means, let me know if I've somehow been unclear concerning list policy vis-a-vis the BARKS database, and I'll be happy to wax yet more poetic while providing hands-on examples.

Closing unfixed.
