### ISSUE TITLE
Same Client, Different Name

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#825]
Please delete Brandi Inman CID 4619 from the system, I will link Goten AID 10372.
The correct spelling is Irman, and I didn't realize she had been in the system already. Could not find her with the spelling she provided over the phone.

**Comment by carl-hamlin** [comment]
Loren, for the most part, this request was properly formatted, and I appreciate your effort.

When we're smoking a duplicate client record, I need the id of the correct record as well, because I have to transfer all of the payment records associated with the dupe over to the correct record. In most cases, it's not that big a deal, I can usually just look the correct record up on my own, but it's an extra step.

Thanks again for kicking ass.
