### ISSUE TITLE
Editing Appointments & Finalized Invoices 

### ISSUE THREAD

**Issue by CMaxeyRVT** [carl-hamlin/barks#97]

**Comment by carl-hamlin** [comment]
It is possible that in the near future, there will be a mechanism for changing the date of an appointment. I will make a separate issue to track development thereupon.

There will never be a way to change the *reason* for an appointment. If the situation has changed drastically since the caretaker made the original appointment, they need a new appointment. The person who originally entered the old appointment can remove it if they wish, and if they don't I'm sure I'll come across it during data audit and figure out what happened, and remove it myself.

There will never, ever, ever be a way for staff to edit finalized appointments. They are referred to as 'finalized', because ostensibly everything that needs to be done to them has been done. That is the nature of 'final'. If staff are finding that they need to edit appointments after the fact, then *the appointments are being finalized too soon*. This is a problem that needs to be addressed in workflow.

At some point in the relatively near future, it will be possible for doctors to re-open visits under which one or more line items are attributed to them. This will take care of the scenario wherein a visit is finalized, then a half hour later, the Dr. changes their mind and wants to make the invoice reflect the change.

The Dr. will have to log in personally to re-open the visit, however, which will hopefully encourage everyone to be more decisive about treatment, and careful about precision data entry.
